import assert from "node:assert/strict";
import { nettoyerPiece, dateValide, proposerAssociations, alertesPiece } from "../../src/lib/justificatifs";
const p = nettoyerPiece({ devise: "EUR", fournisseur: "Vétérinaire Agon", numero: "F1", date: "2026-06-12", ht: 100, tva: 20, ttc: 120 });
const d = { id: "a", fournisseur: "VETERINAIRE AGON", montant: 120, source: "releve-bancaire", dateOperation: "2026-07-02" };
assert.equal(proposerAssociations(p, [d])[0].score, 100);
assert.equal(proposerAssociations(p, [{ ...d, fournisseur: "Autre entreprise" }])[0].score, 60);
assert.equal(proposerAssociations(p, [{ ...d, montant: 60 }]).length, 0);
assert.equal(proposerAssociations(p, [{ ...d, source: "saisie" }]).length, 0);
assert.equal(proposerAssociations({ ...p, ttc: null }, [d]).length, 0);
assert.equal(proposerAssociations({ ...p, ttc: -120 }, [d]).length, 0);
assert.equal(proposerAssociations(p, [d, { ...d, id: "b" }]).length, 2, "Ne pas masquer une ambiguïté");
assert.equal(proposerAssociations(p, [{ ...d, dateOperation: "2026-06-01" }])[0].score, 80);
assert.equal(dateValide("2026-02-30"), "");
assert.equal(nettoyerPiece({ ttc: "120", tva: null }).ttc, null);
assert.equal(nettoyerPiece({ tva: 0 }).tva, 0);
assert.equal(alertesPiece(p).length, 0);
assert.ok(alertesPiece({ ...p, tva: 10 }).some(s => s.includes("HT")));
assert.ok(alertesPiece({ ...p, debutPeriode: "2026-08-01", finPeriode: "2026-07-01" }).some(s => s.includes("inversée")));
assert.equal(proposerAssociations(p, [d])[0].dateOperation, "2026-07-02", "Ne pas changer la date bancaire autour du 30 juin");
console.log("Justificatifs : 15 contrôles réussis");
